# Generated by Django 3.2.5 on 2021-07-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('av_seats', models.CharField(default=5, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('connection', models.CharField(choices=[('Friend', 'Friend'), ('Wife', 'Wife'), ('Roommate', 'Roommate'), ('Family', 'Family'), ('Stranger', 'Stranger')], default='Friend', max_length=12)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('date', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot', verbose_name='timeslot')),
            ],
        ),
    ]
