# Generated by Django 3.2.5 on 2021-07-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.TimeField()),
                ('av_seats', models.CharField(default=5, max_length=2)),
            ],
        ),
    ]
