# Generated by Django 3.2.5 on 2021-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_timeslots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeslots',
            new_name='Timeslot',
        ),
    ]
