# Generated by Django 3.2.5 on 2021-07-08 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_timeslots_timeslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='hours',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
