# Generated by Django 3.2.5 on 2021-07-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210708_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.timeslot', verbose_name='id'),
        ),
    ]
