# Generated by Django 3.2.5 on 2021-07-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_auto_20210717_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='host_slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.cowoslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cowoslot',
            name='host_username',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
