# Generated by Django 3.2.5 on 2021-07-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210708_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
