# Generated by Django 3.2.5 on 2021-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210708_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='connection',
            field=models.CharField(choices=[('Friend', 'Friend'), ('Wife', 'Wife'), ('Roommate', 'Roommate'), ('Family', 'Family'), ('Stranger', 'Stranger')], default='Friend', max_length=12),
        ),
    ]
